#!/bin/bash -e

PATH=/opt/conjur/bin:$PATH

source /conjurize.sh

echo 'y' | keytool -importcert -keystore /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/cacerts -storepass changeit -file /etc/conjur-joshops.pem

/usr/local/tomcat/bin/catalina.sh run
tail -f /usr/local/tomcat/logs/*.log 

 
